[package]
name = "pdf-syntax"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
flate2 = { version = "=1.1.9", default-features = false, features = ["rust_backend"] }
pdf-bytes = { path = "../pdf-bytes" }

[lints]
workspace = true
